{
 "title": "maas",
 "tags": [ "deepseek" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "query": {
     "query": "label_values(up{namespace=\"ske-model\",framework=\"vllm\"}, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "资源组概览",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(kube_node_labels{label_group_id=~\"119|127\"}) by (label_group_id)",
     "legendFormat": "{{label_group_id}} Total"
    },
    {
     "expr": "count((kube_node_status_condition{condition=\"Ready\",status=\"true\"} == 1) * on(node) group_left(label_group_id) kube_node_labels{label_group_id=~\"119|127\"}) by (label_group_id)",
     "legendFormat": "{{label_group_id}} Ready"
    },
    {
     "expr": "count(((kube_node_status_condition{condition=\"Ready\",status=\"false\"} == 1) or on(node) (kube_node_spec_unschedulable == 1)) * on(node) group_left(label_group_id) kube_node_labels{label_group_id=~\"119|127\"}) by (label_group_id)",
     "legendFormat": "{{label_group_id}} NotReady/Cordon"
    }
   ]
  },
  {
   "title": "模型节点占用",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (label_group_id,svc) (label_replace(count((kube_pod_status_ready{namespace=\"ske-model\",condition=\"true\"}==1) * on(namespace,pod) group_left(created_by_name,node) kube_pod_info{namespace=\"ske-model\"} * on(node) group_left(label_group_id) kube_node_labels{label_group_id=~\"119|127\"}) by (label_group_id, created_by_name), \"svc\", \"$1\", \"created_by_name\", \"(.*?)(-[a-f0-9]{8,10})?$\"))"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "label_replace(ceil(sum by (host) (rate(nginx_ingress_controller_request_duration_seconds_count{controller_class=\"k8s.io/ingress-maas\",exported_namespace=\"ske-model\"}[$__rate_interval])) * 60), \"host_short\", \"$1\", \"host\", \"^([^.]+).*\")",
     "legendFormat": "{{host_short}}"
    }
   ]
  },
  {
   "title": "GPU利用率",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(dcu_container_dcu_util{exported_container!=\"\",exported_container!~\".*head-1$\",device_id!=\"\",dcu_pod_namespace=~\"ske-model\"}) by (exported_container)) / (sum((label_replace(kube_pod_container_resource_limits{resource=\"hygon_com_dcu\",namespace=~\"ske-model\",container!~\".*head-1$\"},\"exported_container\",\"$1\",\"container\",\"(.*)\"))) by (exported_container))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "显存占用",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by (exported_container) (\n  dcu_container_mem_util{\n    exported_container!=\"\",\n    device_id!=\"\",\n    dcu_pod_namespace=~\"ske-model\"\n  }\n)\n/\nsum by (exported_container) (\n  label_replace(\n    kube_pod_container_resource_limits{\n      resource=\"hygon_com_dcu\",\n      namespace=~\"ske-model\"\n    },\n    \"exported_container\", \"$1\", \"container\", \"(.+)\"\n  )\n)\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod数",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"ske-model\",deployment=~\"$service\"}) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "排队数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum by (service) (vllm:num_requests_waiting{namespace=\"ske-model\",framework=\"vllm\",service=~\"$service\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "在途请求",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum by (service) (vllm:num_requests_running{namespace=\"ske-model\",framework=\"vllm\",service=~\"$service\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "E2E-P90",
   "type": "timeseries",
   "description": "End to end request latency measured in seconds.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, service) (rate(vllm:e2e_request_latency_seconds_bucket{namespace=\"ske-model\",framework=\"vllm\",service=~\"$service\"}[2m])))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "输入TPS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum by (service) (rate(vllm:prompt_tokens_total{namespace=\"ske-model\",framework=\"vllm\",service=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "输出TPS",
   "type": "timeseries",
   "description": "Number of tokens processed per second",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "sum by (service) (rate(vllm:generation_tokens_total{namespace=\"ske-model\",framework=\"vllm\",service=~\"$service\"}[2m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "TTFT-P90",
   "type": "timeseries",
   "description": "P90  TTFT latency in seconds.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, service) (rate(vllm:time_to_first_token_seconds_bucket{namespace=\"ske-model\",framework=\"vllm\",service=~\"$service\"}[2m])))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "错误率",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(100 * sum by (host) (rate(nginx_ingress_controller_requests{controller_class=\"k8s.io/ingress-maas\",exported_namespace=\"ske-model\",status=~\"4..|5..|4xx|5xx\"}[$__rate_interval])) / clamp_min(sum by (host) (rate(nginx_ingress_controller_requests{controller_class=\"k8s.io/ingress-maas\",exported_namespace=\"ske-model\"}[$__rate_interval])), 1e-6), \"host_short\", \"$1\", \"host\", \"^([^.]+).*\")",
     "legendFormat": "{{host_short}}"
    }
   ]
  }
 ]
}