{
 "title": "节点列表",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "集群", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "集群节点总数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "集群异常节点数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (node) (\n    kube_node_spec_unschedulable == 1\n    or\n    kube_node_status_condition{condition=\"Ready\", status=\"true\"} == 0\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "集群节点列表",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "kube_node_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "集群异常节点",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "kube_node_spec_unschedulable == 1\n    or\n    kube_node_status_condition{condition=\"Ready\", status=\"true\"} == 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "节点不可用列表",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": " sum by (node) (\n  timestamp(kube_node_spec_unschedulable==1 )* 1000\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}