{
 "title": "运营101",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "groupId",
    "query": {
     "query": "label_values(resource_group_node_capacity_cards{groupId!=\"\"},groupId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "节点统计",
   "type": "table",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count((resource_group_node_used_cards{groupId=~\"$groupId\",groupId!=\"\"} == 0) and on(node) max by(node) (kube_node_info)) by (groupId)"
    },
    {
     "expr": "count(((resource_group_node_used_cards{groupId=~\"$groupId\",groupId!=\"\"} > 0) and on(node, groupId) (resource_group_node_used_cards{groupId=~\"$groupId\",groupId!=\"\"} < resource_group_node_capacity_cards{groupId=~\"$groupId\",groupId!=\"\"})) and on(node) max by(node) (kube_node_info)) by (groupId)"
    },
    {
     "expr": "count((resource_group_node_used_cards{groupId=~\"$groupId\",groupId!=\"\"} == on(node, groupId) resource_group_node_capacity_cards{groupId=~\"$groupId\",groupId!=\"\"}) and on(node) max by(node) (kube_node_info)) by (groupId)"
    },
    {
     "expr": "count((max by(node, groupId) (resource_group_node_capacity_cards{groupId=~\"$groupId\",groupId!=\"\"} >= bool 0) and on(node) max by(node) (kube_node_info))) by (groupId)"
    },
    {
     "expr": "sum by(groupId) (\n  (\n    (max by(node) (kube_node_spec_unschedulable) == 1)\n    or\n    (max by(node) (kube_node_status_condition{condition=\"Ready\",status=\"true\"} == bool 0))\n  )\n  * on(node) group_left(groupId) max by(node, groupId) (resource_group_node_capacity_cards{groupId=~\"$groupId\",groupId!=\"\"} >= bool 0)\n)"
    }
   ]
  },
  {
   "title": "加速卡售卖率",
   "type": "timeseries",
   "description": "gpu使用卡数/总gpu卡数",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "(\n  100 * sum by(groupId) (\n    (\n      kube_pod_container_resource_requests{resource=\"hygon_com_dcu\"} != 0\n      and on(pod, namespace) kube_pod_status_phase{phase=\"Running\"}\n      unless on(pod, namespace) kube_pod_deletion_timestamp > 0\n    )\n    * on(node) group_left(groupId)\n      max by(node, groupId) (resource_group_node_capacity_cards{groupId=~\"$groupId\",groupId!=\"\"} >= bool 0)\n  ) / sum by(groupId) (\n    kube_node_status_capacity{resource=\"hygon_com_dcu\"}\n    * on(node) group_left(groupId)\n      max by(node, groupId) (resource_group_node_capacity_cards{groupId=~\"$groupId\",groupId!=\"\"} >= bool 0)\n  )\n)\nand on(groupId)\n(\n  sum by(groupId) (\n    kube_node_status_capacity{resource=\"hygon_com_dcu\"}\n    * on(node) group_left(groupId)\n      max by(node, groupId) (resource_group_node_capacity_cards{groupId=~\"$groupId\",groupId!=\"\"} >= bool 0)\n  ) > 0\n)\nor\n(\n  100 * sum by(groupId) (\n    (\n      kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"} != 0\n      and on(pod, namespace) kube_pod_status_phase{phase=\"Running\"}\n      unless on(pod, namespace) kube_pod_deletion_timestamp > 0\n    )\n    * on(node) group_left(groupId)\n      max by(node, groupId) (resource_group_node_capacity_cards{groupId=~\"$groupId\",groupId!=\"\"} >= bool 0)\n  ) / sum by(groupId) (\n    kube_node_status_capacity{resource=\"nvidia_com_gpu\"}\n    * on(node) group_left(groupId)\n      max by(node, groupId) (resource_group_node_capacity_cards{groupId=~\"$groupId\",groupId!=\"\"} >= bool 0)\n  )\n)\nunless on(groupId)\n(\n  sum by(groupId) (\n    kube_node_status_capacity{resource=\"hygon_com_dcu\"}\n    * on(node) group_left(groupId)\n      max by(node, groupId) (resource_group_node_capacity_cards{groupId=~\"$groupId\",groupId!=\"\"} >= bool 0)\n  ) > 0\n)",
     "legendFormat": "{{groupId}}"
    }
   ]
  },
  {
   "title": "加速卡利用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "(\n  sum by(groupId) (\n    dcu_container_dcu_util\n    * on(node) group_left(groupId)\n      max by(node, groupId) (resource_group_node_capacity_cards{groupId=~\"$groupId\",groupId!=\"\"} >= bool 0)\n  ) / sum by(groupId) (\n    kube_node_status_capacity{resource=\"hygon_com_dcu\"}\n    * on(node) group_left(groupId)\n      max by(node, groupId) (resource_group_node_capacity_cards{groupId=~\"$groupId\",groupId!=\"\"} >= bool 0)\n  )\n)\nand on(groupId)\n(\n  sum by(groupId) (\n    kube_node_status_capacity{resource=\"hygon_com_dcu\"}\n    * on(node) group_left(groupId)\n      max by(node, groupId) (resource_group_node_capacity_cards{groupId=~\"$groupId\",groupId!=\"\"} >= bool 0)\n  ) > 0\n)\nor\n(\n  sum by(groupId) (\n    label_replace(DCGM_FI_DEV_GPU_UTIL{Hostname!=\"\"}, \"node\", \"$1\", \"Hostname\", \"(.+)\")\n    * on(node) group_left(groupId)\n      max by(node, groupId) (resource_group_node_capacity_cards{groupId=~\"$groupId\",groupId!=\"\"} >= bool 0)\n  ) / sum by(groupId) (\n    kube_node_status_capacity{resource=\"nvidia_com_gpu\"}\n    * on(node) group_left(groupId)\n      max by(node, groupId) (resource_group_node_capacity_cards{groupId=~\"$groupId\",groupId!=\"\"} >= bool 0)\n  )\n)\nunless on(groupId)\n(\n  sum by(groupId) (\n    kube_node_status_capacity{resource=\"hygon_com_dcu\"}\n    * on(node) group_left(groupId)\n      max by(node, groupId) (resource_group_node_capacity_cards{groupId=~\"$groupId\",groupId!=\"\"} >= bool 0)\n  ) > 0\n)",
     "legendFormat": "{{groupId}}"
    }
   ]
  },
  {
   "title": "cpu售卖率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "100 * sum by(groupId) (\n  (\n    kube_pod_container_resource_requests{resource=\"cpu\"} != 0\n    and on(pod, namespace) kube_pod_status_phase{phase=\"Running\"}\n    unless on(pod, namespace) kube_pod_deletion_timestamp > 0\n  )\n  * on(node) group_left(groupId)\n    max by(node, groupId) (resource_group_node_capacity_cards{groupId=~\"$groupId\",groupId!=\"\"} >= bool 0)\n) / sum by(groupId) (\n  kube_node_status_capacity{resource=\"cpu\"}\n  * on(node) group_left(groupId)\n    max by(node, groupId) (resource_group_node_capacity_cards{groupId=~\"$groupId\",groupId!=\"\"} >= bool 0)\n)",
     "legendFormat": "{{groupId}}"
    }
   ]
  },
  {
   "title": "cpu利用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "sum by(groupId) (\n  rate(container_cpu_usage_seconds_total{container!=\"\"}[5m])\n  * on(node) group_left(groupId)\n    max by(node, groupId) (resource_group_node_capacity_cards{groupId=~\"$groupId\",groupId!=\"\"} >= bool 0)\n) / sum by(groupId) (\n  kube_node_status_capacity{resource=\"cpu\"}\n  * on(node) group_left(groupId)\n    max by(node, groupId) (resource_group_node_capacity_cards{groupId=~\"$groupId\",groupId!=\"\"} >= bool 0)\n)",
     "legendFormat": "{{groupId}}"
    }
   ]
  },
  {
   "title": "容器卡数统计",
   "type": "table",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_resource_limits{resource=~\"hygon_com_dcu|nvidia_com_gpu\"}\n  * on(node) group_left(groupId)\n    max by(node, groupId) (resource_group_node_capacity_cards{groupId=~\"$groupId\",groupId!=\"\"} >= bool 0)\n) by (pod, resource, namespace, node)\n* on(namespace, pod) group_left(phase)\n  (max(kube_pod_status_phase) by (namespace, pod, phase) == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "空闲节点列表",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "group by(node, groupId) (\n  (resource_group_node_used_cards{groupId=~\"$groupId\",groupId!=\"\"} == 0)\n  and on(node) max by(node) (kube_node_info)\n)"
    }
   ]
  }
 ]
}