apiVersion: v1
kind: Service
metadata:
  name: mc-client
  namespace: ske
  labels:
    app: mc-client
spec:
  clusterIP: None
  selector:
    app: mc-client
  ports:
    - name: noop
      port: 1
      targetPort: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mc-client
  namespace: ske
  labels:
    app: mc-client
spec:
  serviceName: mc-client
  replicas: 2
  selector:
    matchLabels:
      app: mc-client
  template:
    metadata:
      labels:
        app: mc-client
    spec:
      hostNetwork: true
      nodeSelector:
        ex-lb: "true"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: mc-client
                topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      tolerations:
        - operator: Exists
      containers:
        - name: mc
          image: image.ac.com:5000/k8s/ske-model-tool:v2-mc
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "/scripts/runner.sh"]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SHARD_TOTAL
              value: "2"
            - name: MC_LIMIT_UPLOAD
              value: "80MiB"
            - name: MC_LIMIT_DOWNLOAD
              value: "80MiB"
          envFrom:
            - configMapRef:
                name: mc-aliases
            - configMapRef:
                name: http-proxy
                optional: true
          resources:
            requests:
              cpu: 100m
              memory: 2Gi
            limits:
              cpu: "2"
              memory: 2Gi
          volumeMounts:
            - name: sync-script
              mountPath: /scripts
      volumes:
        - name: sync-script
          configMap:
            name: minio-lfs-sync-script
            defaultMode: 0755
