export ARCHFLAGS="-arch arm64"
export CFLAGS="$(echo "$CFLAGS" | sed 's/-arch arm_64/-arch arm64/g')"
export LDFLAGS="$(echo "$LDFLAGS" | sed 's/-arch arm_64/-arch arm64/g')"
export PATH=$HOME/bin:/opt/homebrew/bin:/opt/homebrew/sbin:${KREW_ROOT:-$HOME/.krew}/bin:/Users/humin/.antigravity/antigravity/bin:$PATH
export QWEN_SYSTEM_MD=/Users/humin/.qwen/system.md
export KUBECTL_NODE_SHELL_IMAGE=image.ac.com:5000/k8s/netshoot
alias podel='kubectl delete pod --grace-period=0 --force'
export ZSH="/Users/humin/.oh-my-zsh"
eval "$(/opt/homebrew/bin/brew shellenv)"
export ZSH_COMPDUMP="${HOME}/.zcompdump-${HOST%%.*}-${ZSH_VERSION}-arm64"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home"
ZSH_THEME="robbyrussell"
plugins=(git kubectl npm macos mvn autojump zsh-autosuggestions web-search history)
source $ZSH/oh-my-zsh.sh
export MAVEN_OPTS="-Xms2g -Xmx16g"
export MAVEN_OPTS="$MAVEN_OPTS -Xmx4g"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# pnpm
export PNPM_HOME="/Users/humin/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
export LARK_CLI_NO_PROXY=1


# Proxy settings
# export http_proxy="http://127.0.0.1:7890"
# export https_proxy="http://127.0.0.1:7890"
# export all_proxy="socks5://127.0.0.1:7890"
# export no_proxy="localhost,127.0.0.1,0.0.0.0,::1,.local,10.,28.197.,192.168.,.scnet.cn,.scnet.work,.scnet.com"
# export NO_PROXY="localhost,127.0.0.1,0.0.0.0,::1,.local,10.,28.197.,192.168.,.scnet.cn,.scnet.work,.scnet.com"

# Added by Antigravity
export GEMINI_API_KEY=AIzaSyB5yGHyX4-amj9pL8GKLU5a-n9A83WICxo

export HOMEBREW_AUTO_UPDATE_SECS=86400
export HOMEBREW_NO_ENV_HINTS=1
export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.ustc.edu.cn/brew.git"
export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.ustc.edu.cn/homebrew-core.git"
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.ustc.edu.cn/homebrew-bottles"
export HOMEBREW_API_DOMAIN="https://mirrors.ustc.edu.cn/homebrew-bottles/api"
export PUPPETEER_SKIP_DOWNLOAD=true
export PUPPETEER_EXECUTABLE_PATH="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

alias opencode='cd ~/opencode && OPENCODE_AUTO_APPROVE=true opencode'
alias claude='cd ~/claude && claude --dangerously-skip-permissions'
alias codex='cd ~/codex && codex --yolo'
alias haiku='cd ~/claude && claude --dangerously-skip-permissions --model haiku'
alias kubectx='kubectl config use-context'
