apiVersion: v1
kind: Pod
metadata:
  name: modelscope-download
  namespace: ske-model
spec:
  containers:
  - name: modelscope
    image: image.ac.com:5000/k8s/python-modelscope:3.12
    imagePullPolicy: IfNotPresent
    command:
    - /bin/sh
    - -c
    - |
      modelscope download --model XiaomiMiMo/MiMo-V2.5 --cache_dir /models --max-workers 24
      echo "Download completed at $(date)"
      sleep infinity
    envFrom:
    - configMapRef:
        name: http-proxy
    volumeMounts:
    - name: models
      mountPath: /models
    resources:
      requests:
        memory: "4Gi"
        cpu: "8"
      limits:
        memory: "16Gi"
        cpu: "16"
  volumes:
  - name: models
    hostPath:
      # 修改为目标集群的共享存储路径
      path: /work2/ai_data/models
      type: DirectoryOrCreate
  restartPolicy: Never
